### PR TITLE
Make script compatible with GM4

### PR DESCRIPTION
**Pull request by rafaelgomesxyz**

### CODE REVIEW

**Comment by bberenz** [comment]
Hmm, wrapping the entire script in an async function seems like the wrong way to handle this. I'll need to look into what GM4 is doing before I decide on this though.

**Comment by gsrafael01** [comment]
On GM4, all methods return a promise. Wrapping the code in an async function allows you to wait for the promises with `await` before proceeding to the next line of the code, and therefore does not mess with the flow of the code. The other way to do this is to use promise callbacks (`promise.then(() => {})`), but this messes with the flow of the code, because you have to move all of the code that proceeds the call to inside of the callback.

So the async solution is the best one because it does not interfere with the flow of the code. I don't know why you have the impression that it's the wrong way to handle it.

**Comment by bberenz** [comment]
My issue isn't with the use of async/await so much as it is with wrapping the _entire_ script in an asynchronous function - which can cause hard to track bugs later on - just to force 3 calls to be synchronous, none of which would really have issues changing to use a promise callback. (GM.addStyle also [doesn't exist in GM4](https://wiki.greasespot.net/GM_addStyle), so not sure why you added that?)

The `setValue` reapplies settings after completing, which makes sense to directly become the callback. And the OPTION's `getValue` calls are only ever called on start, so they can be grouped in a `Promise.all` with the callback being the actual script initialization.

My experience with javascript tells me to not try to make asynchronous code synchronous, so I'm going to reject this in favor of my own changes. I hope this explanation of why makes sense.

**Comment by gsrafael01** [comment]
Can you be specific about how it can cause hard to track bugs? I've never faced that with ESGST and almost all of its functions are async, so I don't see the correlation. It's literally just a function like any other, and would generate traceable errors like any other.

GM.addStyle comes from the polyfill that is required at the header.

Not sure why your experience tells you that. Mine tells me to always try to make asynchronous code "synchronous" (because it's not, really, it just looks synchronous), because callback hell is a real problem and async/await came to fix that.

It doesn't really make sense for me, but it's your project, so ok.

**Comment by bberenz** [comment]
> Can you be specific about how it can cause hard to track bugs ... It's literally just a function like any other, and generates traceable errors like any other.

Async calls by their nature tend to have an incomplete stack trace when there's a problem, since the calling function could be from anywhere, anytime in the past. I'll grant you it's less of an issue with promises that can reject, but there's also the fact that adding `async` to functions does change their signatures and if you aren't designing around the fact that they now return immediately, things can start  getting called out of order.

> I've never faced that with ESGST and almost all of its functions are async

You've also compartmentalized and designed those functions and calls around that design, rather than wrapping it around everything as a stopgap.

> Not sure why your experience tells you that.

Because I've had legacy project requirements (pre-ES6) that required simulating asynchronous calls as synchronous? It doesn't work very well.  

> because callback hell is a real problem and async / await came to fix that.

To be fair, promises did a lot to save us from callback hell, and async/await can be used to help further to  reduce the boilerplate from them.
Its entirely possible to have done what I did with an async function block that only encompasses the initialization code and the save click callback, but I feel as though having the promise boilerplate around them helps make the intent a little easier to read without potentially changing how the outer functions get called.

Ultimately, with the current codebase, it comes down to a style choice, but I have long gaps between working on these scripts and want to keep them as clear as possible to quickly get back up to speed when I do get back to them since, as you said, it is my project and I am the one that has to maintain it.

**Comment by gsrafael01** [comment]
>> Async calls by their nature tend to have an incomplete stack trace when there's a problem, since the calling function could be from anywhere, anytime in the past.

That's not true, though. The stack traces I get with async functions are just as complete as normal ones. It doesn't matter where the function was called from, that information is always available. They're actually easier to debug, because you can just wrap them in a try / catch block and all of the exceptions will be caught.

>  there's also the fact that adding `async` to functions does change their signatures and if you aren't designing around the fact that they now return immediately, things can start getting called out of order.

That's what `await` is for. As long as you locate all of the usages of the function and add `await` to their call (then recursively doing this to the functions that they're inside of - something that can be quickly done with search & replace), there's absolutely no way that things can start getting called out of order. That's the whole point of async / await, the simplicity that it provides.

> You've also compartmentalized and designed those functions and calls around that design, rather than wrapping it around everything as a stopgap.

Only now that ESGST is modular, but when it was only one file, the entire code was wrapped in an async function, and I never had any problems. It's not a "stopgag", it's a real solution that has zero consequences, and also allows for better readability and maintainability, because if you ever need to add more asynchronous code, the base is already there.

Also, wrapping the entire script around a function is something that has always been recommended by most userscript managers (Tampermonkey automatically adds a wrapping function when you create a new script), because that allows you to separate your script from external sources and potential headache. Adding `async` to that function changes nothing.

> Because I've had legacy project requirements (pre-ES6) that required simulating asynchronous calls as synchronous? It doesn't work very well.

How is that relevant if async / await only came with ES6?

> Ultimately, with the current codebase, it comes down to a style choice, but I have long gaps between working on these scripts and want to keep them as clear as possible to quickly get back up to speed when I do get back to them since, as you said, it is my project and I am the one that has to maintain it.

I still don't understand why you think that promises are clearer to read and better to maintain than async / await... ¯\\\_(ツ)_/¯

**Pull request closed without merging**
